jhipster/generator-jhipster-module

- generators/app/index.js
add store option to save username
fix #6
> add store option to save username

- generators/app/index.js
- generators/app/templates/_package.json
- generators/app/templates/generators/app/_index.js
- generators/app/templates/generators/entity/_index.js
- package.json
- yarn.lock
The generator template & the generator have been updated to Yeoman Generator 2.0
> upgrade to Yeoman generator 2.0

- generators/app/index.js
- generators/app/input-validation.js
- test/input-validation.spec.js
updated regex to match github's username validation, extracted validation methods into separate js file to enable unit testing, added unit testing for github username validation
Fix #22
> github username validation fix

- generators/app/templates/_package.json
Resolve error npm test script https://github.com/jhipster/generator-jhipster-module/issues/24#issuecomment-425360697
> Resolve error for test running after generation

- .travis.yml
- generators/app/templates/_travis.yml
Related to https://github.com/jhipster/generator-jhipster/pull/9052
> Upgrade to Node 10.15.0

- .travis.yml
- generators/app/templates/_travis.yml
Related to https://github.com/jhipster/generator-jhipster/pull/9474
> Upgrade to Node 10.15.3

- README.md
- azure-pipelines.yml
Fix #32 
We also need to init the pipeline on Azure.
> CI migration: Azure pipelines

- .travis.yml
- azure-pipelines.yml
- generators/app/templates/_travis.yml
Related with jhipster/generator-jhipster#9816
> Update Node to 10.16.0

- .travis.yml
- azure-pipelines.yml
- generators/app/templates/_travis.yml
Related to https://github.com/jhipster/generator-jhipster/pull/10173
> Update Node version to 10.16.1

- .travis.yml
- azure-pipelines.yml
- generators/app/templates/_travis.yml
Related to https://github.com/jhipster/generator-jhipster/pull/10206
> Upgrade to Node 10.16.2

- .travis.yml
- azure-pipelines.yml
- generators/app/templates/_travis.yml
Related to https://github.com/jhipster/generator-jhipster/pull/10236
> Update Node version to 10.16.3

- .travis.yml
- azure-pipelines.yml
- generators/app/templates/_travis.yml
Related to https://github.com/jhipster/generator-jhipster/pull/10707
> update Node version to v12.13.0

- .travis.yml
- azure-pipelines.yml
- generators/app/templates/_travis.yml
Related to https://github.com/jhipster/generator-jhipster/pull/10851
> Upgrade to NodeJS 12.13.1 LTS

- generators/app/index.js
- generators/app/templates/.github/workflows/github-ci.yml.ejs
- test/app.spec.js
> Add GitHub CI workflow for generated module

- generators/app/templates/generators/app/_index.js
- generators/app/templates/generators/entity/_index.js
fixes https://github.com/jhipster/generator-jhipster-module/issues/53
> fix: build npm test

- .travis.yml
- azure-pipelines.yml
- generators/app/templates/_travis.yml
Related with https://github.com/jhipster/generator-jhipster/pull/11067
> Update node to version 12.14.0 LTS

- .github/workflows/github-ci.yml
- azure-pipelines.yml
- generators/generator-constants.js
Related to https://github.com/jhipster/generator-jhipster/pull/11328
> Upgrade to Node.js 12.16.0 LTS

- .github/workflows/github-ci.yml
- azure-pipelines.yml
- generators/generator-constants.js
Related to jhipster/generator-jhipster#11428
> Upgrade to Node.js 12.16.1 LTS

- .github/workflows/release-drafter.yml
- README.md
Related to https://github.com/jhipster/generator-jhipster/issues/11935
> Change default branch from master to main

- .github/workflows/github-ci.yml
- generators/generator-constants.js
related to https://github.com/jhipster/generator-jhipster/issues/12877
> Upgrade to Node 14.15.0 LTS

- .github/workflows/github-ci.yml
- generators/generator-constants.js
Related with https://github.com/jhipster/generator-jhipster/issues/14304
> Update Nodejs version to 14.16.0

- generators/app/index.js
- generators/app/templates/.github/workflows/github-ci.yml.ejs
- generators/app/templates/generators/app/index.js.ejs
- generators/app/templates/generators/entity/index.js.ejs
- generators/app/templates/package.json.ejs
- generators/app/templates/test/app.spec.js.ejs
- generators/app/templates/test/templates/maven-vue/.yo-rc.json
- package.json
fix https://github.com/jhipster/generator-jhipster/issues/14327
> Move to jhipster v7

- LICENSE
- NOTICE
- related to https://github.com/jhipster/generator-jhipster/issues/17509
> Update License to 2022
